import { createRequire } from 'node:module';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
const modules=process.env.PLAYWRIGHT_MODULES || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules');
const require=createRequire(path.join(modules,'playwright/package.json'));
const { chromium }=require('playwright');
const candidates=[process.env.FLYCALC_BROWSER,'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Google/Chrome/Application/chrome.exe'].filter(Boolean);
const executablePath=candidates.find(existsSync);
if(!executablePath)throw new Error('No Chromium/Edge executable found. Set FLYCALC_BROWSER.');
mkdirSync('output/screenshots',{recursive:true});
const browser=await chromium.launch({executablePath,headless:true});
const page=await browser.newPage({viewport:{width:1430,height:1000}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const address='http://127.0.0.1:8147';
try {
  await page.goto(address);
  await page.getByText('Локальный сервис подключён',{exact:true}).waitFor();
  assert.equal(await page.locator('select option').count(),6);
  await page.screenshot({path:'output/screenshots/windows-preview.png',fullPage:true});
  await page.getByLabel('ICAO вылета').fill('ZZZZ');
  await page.getByRole('button',{name:'Проверить рейс'}).click();
  await page.getByRole('alert').filter({hasText:'Аэропорт не найден: ZZZZ'}).waitFor();
  await page.getByLabel('ICAO вылета').fill('UUEE');
  await page.getByRole('button',{name:'Проверить рейс'}).click();
  await page.getByRole('heading',{name:'Связь проверена'}).waitFor();
  assert.equal(await page.getByText('Не рассчитано',{exact:true}).count(),4);
  await page.getByRole('button',{name:'Открыть тестовый документ'}).click();
  await page.locator('.fc-doc-view img').waitFor();
  await page.waitForFunction(()=>{const img=document.querySelector('.fc-doc-view img');return img && img.complete && img.naturalWidth>0;});
  await page.screenshot({path:'output/screenshots/documents-preview.png',fullPage:true});
  await page.goto(address+'/fenix');
  await page.setViewportSize({width:2028,height:1536});
  await page.getByText('Локальный сервис подключён',{exact:true}).waitFor();
  assert.equal(await page.locator('select').inputValue(),'fenix-a320');
  assert.ok(await page.getByText('Добавление вкладки в штатный планшет самолёта пока не подтверждено.',{exact:false}).count());
  await page.screenshot({path:'output/screenshots/fenix-preview.png',fullPage:true});
  await page.goto(address+'/?display=flypad');
  await page.setViewportSize({width:1430,height:1000});
  await page.getByText('Локальный сервис подключён',{exact:true}).waitFor();
  assert.equal(await page.locator('.fc-embedded').count(),1);
  await page.screenshot({path:'output/screenshots/flypad-layout-preview.png',fullPage:true});
  await page.setViewportSize({width:760,height:900});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
  await page.route('**/api/v1/status',route=>route.abort());
  await page.goto(address);
  await page.getByRole('alert').waitFor();
  await page.unroute('**/api/v1/status');
  await page.getByRole('button',{name:'Переподключить'}).click();
  await page.getByRole('button',{name:'Проверить рейс'}).waitFor();
  await page.waitForFunction(()=>!document.querySelector('.fc-primary').disabled);
  assert.deepEqual(errors,[]);
  writeFileSync('evidence/ui-validation.json',JSON.stringify({status:'passed',engine:'Microsoft Edge / Chromium',flypadRuntime:'not_tested',fenixCockpit:'not_tested',viewports:[[1430,1000],[2028,1536],[760,900]],checks:['ICAO validation','six aircraft','probe has no calculated values','PDF page image','Fenix display disclosure and default profile','embedded flyPad layout preview','responsive width','reconnection'],pageErrors:errors},null,2)+'\n');
  console.log('Browser UI checks passed, including PDF display and reconnection. Not an in-simulator check.');
} finally { await browser.close(); }
